import pandas as pd
import numpy as np

class RealWorldDataLoader:
    """
    Simulates loading real-world datasets via pandas. 
    In a fully operational environment, this reads CSVs generated by the Apache Airflow data pipeline.
    """
    def __init__(self):
        # We mock the data here since the actual data pipeline isn't fully populated yet.
        pass
        
    def get_gdp_history(self):
        """Returns real-world GDP quarterly history (in Trillions USD)"""
        # Mocking a pandas read_csv
        df = pd.DataFrame({
            'Quarter': ['Q1', 'Q2', 'Q3', 'Q4', 'Q1', 'Q2', 'Q3'],
            'GDP_Trillions': [20.0, 20.2, 20.5, 20.7, 21.1, 21.4, 21.8]
        })
        return df['GDP_Trillions'].tolist()
        
    def get_market_volatility(self):
        """Returns recent market volatility index (VIX-like) history"""
        df = pd.DataFrame({
            'Month': [1, 2, 3, 4, 5, 6],
            'Volatility': [0.1, 0.12, 0.15, 0.14, 0.55, 0.60]
        })
        return df['Volatility'].tolist()
        
    def fetch_imf_data(self):
        """IMF (International Monetary Fund) for Global Inflation & GDP Adjustments"""
        return {"global_inflation": 0.045, "gdp_growth": 0.02}
        
    def fetch_un_population(self):
        """UN Population Division for Demographics & Migration"""
        return {"global_pop": 8000000000, "growth_rate": 0.011}
        
    def fetch_who_health_data(self):
        """WHO (World Health Organization) for Pandemic & Mortality baselines"""
        return {"base_mortality": 0.008, "pandemic_risk_index": 0.2}
        
    def fetch_noaa_climate(self):
        """NOAA for Global Temperature Anomalies & CO2 PPM"""
        return {"co2_ppm": 419.0, "temp_anomaly": +1.1}
        
    def fetch_gdelt_events(self):
        """GDELT Project for Real-Time Geopolitical Conflict Tracking"""
        import requests
        import random
        import urllib.parse
        
        fallback_events = [
            {"event": "Russia-Ukraine Conflict Intensifies", "severity": 8.5},
            {"event": "China-Taiwan Naval Standoff Escalates", "severity": 9.0},
            {"event": "Middle East Tensions Disrupt Oil Routes", "severity": 8.0},
            {"event": "India-Pakistan Border Skirmish Reported", "severity": 7.5}
        ]
        
        try:
            query = '"Russia" OR "Ukraine" OR "Taiwan" OR "Israel" OR "Pakistan"'
            url = f"https://api.gdeltproject.org/api/v2/doc/doc?query={urllib.parse.quote(query)}&mode=artlist&maxrecords=4&format=json"
            response = requests.get(url, timeout=3)
            events = []
            if response.status_code == 200:
                data = response.json()
                for article in data.get("articles", []):
                    title = article.get("title", "Geopolitical Incident")
                    events.append({"event": title, "severity": random.uniform(6.0, 9.5)})
            if events:
                return events
            return fallback_events
        except Exception:
            return fallback_events
        
    def fetch_iea_energy(self):
        """IEA (International Energy Agency) for Global Energy Mix & Crude Stocks"""
        return {"oil_reserves": 1500, "renewable_mix": 0.28}
        
    def get_global_trade_matrix(self):
        """Returns the UN Comtrade global export/import volume matrix"""
        # UN Comtrade (rows=from, cols=to for USA, China, EU, Russia, India)
        matrix = np.array([
            [0.0, 0.2, 0.4, 0.1, 0.3], # USA
            [0.4, 0.0, 0.3, 0.2, 0.1], # China
            [0.3, 0.3, 0.0, 0.2, 0.2], # EU
            [0.1, 0.4, 0.3, 0.0, 0.2], # Russia
            [0.2, 0.1, 0.2, 0.5, 0.0]  # India
        ])
        return matrix
