"""initial schema

Revision ID: ba1594898922
Revises: 
Create Date: 2026-07-09 12:56:10.174447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba1594898922'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('iso_code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('iso_code'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_countries_iso_code'), 'countries', ['iso_code'], unique=False)
    
    op.create_table('global_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.Float(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_global_events_active', 'global_events', ['active'], unique=False)
    op.create_index('idx_global_events_category', 'global_events', ['category'], unique=False)
    
    op.create_table('economic_time_series',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('country_code', sa.String(length=3), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('gdp_usd', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('inflation_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('unemployment_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['country_code'], ['countries.iso_code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_economic_country_year', 'economic_time_series', ['country_code', 'year'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_economic_country_year', table_name='economic_time_series')
    op.drop_table('economic_time_series')
    op.drop_index('idx_global_events_category', table_name='global_events')
    op.drop_index('idx_global_events_active', table_name='global_events')
    op.drop_table('global_events')
    op.drop_index(op.f('ix_countries_iso_code'), table_name='countries')
    op.drop_table('countries')
    # ### end Alembic commands ###
