/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWorldRouteImport } from './routes/app.world'
import { Route as AppTradeRouteImport } from './routes/app.trade'
import { Route as AppSimulationRouteImport } from './routes/app.simulation'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppScenarioRouteImport } from './routes/app.scenario'
import { Route as AppRiskRouteImport } from './routes/app.risk'
import { Route as AppResultsRouteImport } from './routes/app.results'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppPoliticsRouteImport } from './routes/app.politics'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppMonteCarloRouteImport } from './routes/app.monte-carlo'
import { Route as AppEconomyRouteImport } from './routes/app.economy'
import { Route as AppDesignSystemRouteImport } from './routes/app.design-system'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppClimateRouteImport } from './routes/app.climate'
import { Route as AppAiRouteImport } from './routes/app.ai'
import { Route as AppAgentsRouteImport } from './routes/app.agents'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AuthRegisterRouteImport } from './routes/_auth.register'
import { Route as AuthMfaRouteImport } from './routes/_auth.mfa'
import { Route as AuthLoginRouteImport } from './routes/_auth.login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth.forgot-password'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorldRoute = AppWorldRouteImport.update({
  id: '/world',
  path: '/world',
  getParentRoute: () => AppRoute,
} as any)
const AppTradeRoute = AppTradeRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => AppRoute,
} as any)
const AppSimulationRoute = AppSimulationRouteImport.update({
  id: '/simulation',
  path: '/simulation',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppScenarioRoute = AppScenarioRouteImport.update({
  id: '/scenario',
  path: '/scenario',
  getParentRoute: () => AppRoute,
} as any)
const AppRiskRoute = AppRiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => AppRoute,
} as any)
const AppResultsRoute = AppResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppPoliticsRoute = AppPoliticsRouteImport.update({
  id: '/politics',
  path: '/politics',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppMonteCarloRoute = AppMonteCarloRouteImport.update({
  id: '/monte-carlo',
  path: '/monte-carlo',
  getParentRoute: () => AppRoute,
} as any)
const AppEconomyRoute = AppEconomyRouteImport.update({
  id: '/economy',
  path: '/economy',
  getParentRoute: () => AppRoute,
} as any)
const AppDesignSystemRoute = AppDesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppClimateRoute = AppClimateRouteImport.update({
  id: '/climate',
  path: '/climate',
  getParentRoute: () => AppRoute,
} as any)
const AppAiRoute = AppAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsRoute = AppAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMfaRoute = AuthMfaRouteImport.update({
  id: '/mfa',
  path: '/mfa',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/mfa': typeof AuthMfaRoute
  '/register': typeof AuthRegisterRoute
  '/app/admin': typeof AppAdminRoute
  '/app/agents': typeof AppAgentsRoute
  '/app/ai': typeof AppAiRoute
  '/app/climate': typeof AppClimateRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/design-system': typeof AppDesignSystemRoute
  '/app/economy': typeof AppEconomyRoute
  '/app/monte-carlo': typeof AppMonteCarloRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/politics': typeof AppPoliticsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/results': typeof AppResultsRoute
  '/app/risk': typeof AppRiskRoute
  '/app/scenario': typeof AppScenarioRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/simulation': typeof AppSimulationRoute
  '/app/trade': typeof AppTradeRoute
  '/app/world': typeof AppWorldRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/mfa': typeof AuthMfaRoute
  '/register': typeof AuthRegisterRoute
  '/app/admin': typeof AppAdminRoute
  '/app/agents': typeof AppAgentsRoute
  '/app/ai': typeof AppAiRoute
  '/app/climate': typeof AppClimateRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/design-system': typeof AppDesignSystemRoute
  '/app/economy': typeof AppEconomyRoute
  '/app/monte-carlo': typeof AppMonteCarloRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/politics': typeof AppPoliticsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/results': typeof AppResultsRoute
  '/app/risk': typeof AppRiskRoute
  '/app/scenario': typeof AppScenarioRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/simulation': typeof AppSimulationRoute
  '/app/trade': typeof AppTradeRoute
  '/app/world': typeof AppWorldRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/mfa': typeof AuthMfaRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/app/admin': typeof AppAdminRoute
  '/app/agents': typeof AppAgentsRoute
  '/app/ai': typeof AppAiRoute
  '/app/climate': typeof AppClimateRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/design-system': typeof AppDesignSystemRoute
  '/app/economy': typeof AppEconomyRoute
  '/app/monte-carlo': typeof AppMonteCarloRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/politics': typeof AppPoliticsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/results': typeof AppResultsRoute
  '/app/risk': typeof AppRiskRoute
  '/app/scenario': typeof AppScenarioRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/simulation': typeof AppSimulationRoute
  '/app/trade': typeof AppTradeRoute
  '/app/world': typeof AppWorldRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/mfa'
    | '/register'
    | '/app/admin'
    | '/app/agents'
    | '/app/ai'
    | '/app/climate'
    | '/app/dashboard'
    | '/app/design-system'
    | '/app/economy'
    | '/app/monte-carlo'
    | '/app/notifications'
    | '/app/politics'
    | '/app/reports'
    | '/app/results'
    | '/app/risk'
    | '/app/scenario'
    | '/app/settings'
    | '/app/simulation'
    | '/app/trade'
    | '/app/world'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/mfa'
    | '/register'
    | '/app/admin'
    | '/app/agents'
    | '/app/ai'
    | '/app/climate'
    | '/app/dashboard'
    | '/app/design-system'
    | '/app/economy'
    | '/app/monte-carlo'
    | '/app/notifications'
    | '/app/politics'
    | '/app/reports'
    | '/app/results'
    | '/app/risk'
    | '/app/scenario'
    | '/app/settings'
    | '/app/simulation'
    | '/app/trade'
    | '/app/world'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/app'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/mfa'
    | '/_auth/register'
    | '/app/admin'
    | '/app/agents'
    | '/app/ai'
    | '/app/climate'
    | '/app/dashboard'
    | '/app/design-system'
    | '/app/economy'
    | '/app/monte-carlo'
    | '/app/notifications'
    | '/app/politics'
    | '/app/reports'
    | '/app/results'
    | '/app/risk'
    | '/app/scenario'
    | '/app/settings'
    | '/app/simulation'
    | '/app/trade'
    | '/app/world'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/world': {
      id: '/app/world'
      path: '/world'
      fullPath: '/app/world'
      preLoaderRoute: typeof AppWorldRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/trade': {
      id: '/app/trade'
      path: '/trade'
      fullPath: '/app/trade'
      preLoaderRoute: typeof AppTradeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/simulation': {
      id: '/app/simulation'
      path: '/simulation'
      fullPath: '/app/simulation'
      preLoaderRoute: typeof AppSimulationRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/scenario': {
      id: '/app/scenario'
      path: '/scenario'
      fullPath: '/app/scenario'
      preLoaderRoute: typeof AppScenarioRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/risk': {
      id: '/app/risk'
      path: '/risk'
      fullPath: '/app/risk'
      preLoaderRoute: typeof AppRiskRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/results': {
      id: '/app/results'
      path: '/results'
      fullPath: '/app/results'
      preLoaderRoute: typeof AppResultsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/politics': {
      id: '/app/politics'
      path: '/politics'
      fullPath: '/app/politics'
      preLoaderRoute: typeof AppPoliticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/monte-carlo': {
      id: '/app/monte-carlo'
      path: '/monte-carlo'
      fullPath: '/app/monte-carlo'
      preLoaderRoute: typeof AppMonteCarloRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/economy': {
      id: '/app/economy'
      path: '/economy'
      fullPath: '/app/economy'
      preLoaderRoute: typeof AppEconomyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/design-system': {
      id: '/app/design-system'
      path: '/design-system'
      fullPath: '/app/design-system'
      preLoaderRoute: typeof AppDesignSystemRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/climate': {
      id: '/app/climate'
      path: '/climate'
      fullPath: '/app/climate'
      preLoaderRoute: typeof AppClimateRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ai': {
      id: '/app/ai'
      path: '/ai'
      fullPath: '/app/ai'
      preLoaderRoute: typeof AppAiRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agents': {
      id: '/app/agents'
      path: '/agents'
      fullPath: '/app/agents'
      preLoaderRoute: typeof AppAgentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/mfa': {
      id: '/_auth/mfa'
      path: '/mfa'
      fullPath: '/mfa'
      preLoaderRoute: typeof AuthMfaRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthMfaRoute: typeof AuthMfaRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthMfaRoute: AuthMfaRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAgentsRoute: typeof AppAgentsRoute
  AppAiRoute: typeof AppAiRoute
  AppClimateRoute: typeof AppClimateRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDesignSystemRoute: typeof AppDesignSystemRoute
  AppEconomyRoute: typeof AppEconomyRoute
  AppMonteCarloRoute: typeof AppMonteCarloRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPoliticsRoute: typeof AppPoliticsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppResultsRoute: typeof AppResultsRoute
  AppRiskRoute: typeof AppRiskRoute
  AppScenarioRoute: typeof AppScenarioRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSimulationRoute: typeof AppSimulationRoute
  AppTradeRoute: typeof AppTradeRoute
  AppWorldRoute: typeof AppWorldRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAgentsRoute: AppAgentsRoute,
  AppAiRoute: AppAiRoute,
  AppClimateRoute: AppClimateRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDesignSystemRoute: AppDesignSystemRoute,
  AppEconomyRoute: AppEconomyRoute,
  AppMonteCarloRoute: AppMonteCarloRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPoliticsRoute: AppPoliticsRoute,
  AppReportsRoute: AppReportsRoute,
  AppResultsRoute: AppResultsRoute,
  AppRiskRoute: AppRiskRoute,
  AppScenarioRoute: AppScenarioRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSimulationRoute: AppSimulationRoute,
  AppTradeRoute: AppTradeRoute,
  AppWorldRoute: AppWorldRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
