from airflow import DAG # type: ignore
from airflow.providers.standard.operators.python import PythonOperator # type: ignore
from datetime import datetime, timedelta
import sys
import os

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'scripts', 'collectors')))

def run_gdelt_collector():
    from gdelt_collector import GdeltCollector
    collector = GdeltCollector()
    # GDELT events can just append (id is UUID PK generated by DB default if not provided)
    # Note: If collector needs conflict_cols, we can provide it, but append is fine.
    collector.execute()

default_args = {
    'owner': 'data_team',
    'depends_on_past': False,
    'start_date': datetime(2025, 1, 1),
    'retries': 3,
    'retry_delay': timedelta(minutes=5),
    'execution_timeout': timedelta(minutes=30)
}

with DAG(
    'gdelt_ingestion',
    default_args=default_args,
    schedule='@daily',
    catchup=False,
    tags=['geopolitics', 'gdelt'],
) as dag:

    fetch_task = PythonOperator(
        task_id='fetch_and_load_gdelt',
        python_callable=run_gdelt_collector
    )
