/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SimulationsRouteImport } from './routes/simulations'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as RolesRouteImport } from './routes/roles'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as OrganizationsRouteImport } from './routes/organizations'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MonteCarloRouteImport } from './routes/monte-carlo'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as IntelligenceRouteImport } from './routes/intelligence'
import { Route as InfrastructureRouteImport } from './routes/infrastructure'
import { Route as ForecastRouteImport } from './routes/forecast'
import { Route as DigitalTwinRouteImport } from './routes/digital-twin'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as DatabasesRouteImport } from './routes/databases'
import { Route as DataSourcesRouteImport } from './routes/data-sources'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as ApiGatewayRouteImport } from './routes/api-gateway'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as IndexRouteImport } from './routes/index'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulationsRoute = SimulationsRouteImport.update({
  id: '/simulations',
  path: '/simulations',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoute = RolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsRoute = OrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MonteCarloRoute = MonteCarloRouteImport.update({
  id: '/monte-carlo',
  path: '/monte-carlo',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelligenceRoute = IntelligenceRouteImport.update({
  id: '/intelligence',
  path: '/intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const InfrastructureRoute = InfrastructureRouteImport.update({
  id: '/infrastructure',
  path: '/infrastructure',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastRoute = ForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalTwinRoute = DigitalTwinRouteImport.update({
  id: '/digital-twin',
  path: '/digital-twin',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const DatabasesRoute = DatabasesRouteImport.update({
  id: '/databases',
  path: '/databases',
  getParentRoute: () => rootRouteImport,
} as any)
const DataSourcesRoute = DataSourcesRouteImport.update({
  id: '/data-sources',
  path: '/data-sources',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGatewayRoute = ApiGatewayRouteImport.update({
  id: '/api-gateway',
  path: '/api-gateway',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/agents': typeof AgentsRoute
  '/api-gateway': typeof ApiGatewayRoute
  '/billing': typeof BillingRoute
  '/data-sources': typeof DataSourcesRoute
  '/databases': typeof DatabasesRoute
  '/design-system': typeof DesignSystemRoute
  '/digital-twin': typeof DigitalTwinRoute
  '/forecast': typeof ForecastRoute
  '/infrastructure': typeof InfrastructureRoute
  '/intelligence': typeof IntelligenceRoute
  '/models': typeof ModelsRoute
  '/monte-carlo': typeof MonteCarloRoute
  '/notifications': typeof NotificationsRoute
  '/organizations': typeof OrganizationsRoute
  '/reports': typeof ReportsRoute
  '/roles': typeof RolesRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/simulations': typeof SimulationsRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/agents': typeof AgentsRoute
  '/api-gateway': typeof ApiGatewayRoute
  '/billing': typeof BillingRoute
  '/data-sources': typeof DataSourcesRoute
  '/databases': typeof DatabasesRoute
  '/design-system': typeof DesignSystemRoute
  '/digital-twin': typeof DigitalTwinRoute
  '/forecast': typeof ForecastRoute
  '/infrastructure': typeof InfrastructureRoute
  '/intelligence': typeof IntelligenceRoute
  '/models': typeof ModelsRoute
  '/monte-carlo': typeof MonteCarloRoute
  '/notifications': typeof NotificationsRoute
  '/organizations': typeof OrganizationsRoute
  '/reports': typeof ReportsRoute
  '/roles': typeof RolesRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/simulations': typeof SimulationsRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/agents': typeof AgentsRoute
  '/api-gateway': typeof ApiGatewayRoute
  '/billing': typeof BillingRoute
  '/data-sources': typeof DataSourcesRoute
  '/databases': typeof DatabasesRoute
  '/design-system': typeof DesignSystemRoute
  '/digital-twin': typeof DigitalTwinRoute
  '/forecast': typeof ForecastRoute
  '/infrastructure': typeof InfrastructureRoute
  '/intelligence': typeof IntelligenceRoute
  '/models': typeof ModelsRoute
  '/monte-carlo': typeof MonteCarloRoute
  '/notifications': typeof NotificationsRoute
  '/organizations': typeof OrganizationsRoute
  '/reports': typeof ReportsRoute
  '/roles': typeof RolesRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/simulations': typeof SimulationsRoute
  '/users': typeof UsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/agents'
    | '/api-gateway'
    | '/billing'
    | '/data-sources'
    | '/databases'
    | '/design-system'
    | '/digital-twin'
    | '/forecast'
    | '/infrastructure'
    | '/intelligence'
    | '/models'
    | '/monte-carlo'
    | '/notifications'
    | '/organizations'
    | '/reports'
    | '/roles'
    | '/security'
    | '/settings'
    | '/simulations'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/agents'
    | '/api-gateway'
    | '/billing'
    | '/data-sources'
    | '/databases'
    | '/design-system'
    | '/digital-twin'
    | '/forecast'
    | '/infrastructure'
    | '/intelligence'
    | '/models'
    | '/monte-carlo'
    | '/notifications'
    | '/organizations'
    | '/reports'
    | '/roles'
    | '/security'
    | '/settings'
    | '/simulations'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/agents'
    | '/api-gateway'
    | '/billing'
    | '/data-sources'
    | '/databases'
    | '/design-system'
    | '/digital-twin'
    | '/forecast'
    | '/infrastructure'
    | '/intelligence'
    | '/models'
    | '/monte-carlo'
    | '/notifications'
    | '/organizations'
    | '/reports'
    | '/roles'
    | '/security'
    | '/settings'
    | '/simulations'
    | '/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  AgentsRoute: typeof AgentsRoute
  ApiGatewayRoute: typeof ApiGatewayRoute
  BillingRoute: typeof BillingRoute
  DataSourcesRoute: typeof DataSourcesRoute
  DatabasesRoute: typeof DatabasesRoute
  DesignSystemRoute: typeof DesignSystemRoute
  DigitalTwinRoute: typeof DigitalTwinRoute
  ForecastRoute: typeof ForecastRoute
  InfrastructureRoute: typeof InfrastructureRoute
  IntelligenceRoute: typeof IntelligenceRoute
  ModelsRoute: typeof ModelsRoute
  MonteCarloRoute: typeof MonteCarloRoute
  NotificationsRoute: typeof NotificationsRoute
  OrganizationsRoute: typeof OrganizationsRoute
  ReportsRoute: typeof ReportsRoute
  RolesRoute: typeof RolesRoute
  SecurityRoute: typeof SecurityRoute
  SettingsRoute: typeof SettingsRoute
  SimulationsRoute: typeof SimulationsRoute
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulations': {
      id: '/simulations'
      path: '/simulations'
      fullPath: '/simulations'
      preLoaderRoute: typeof SimulationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles': {
      id: '/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations': {
      id: '/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof OrganizationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monte-carlo': {
      id: '/monte-carlo'
      path: '/monte-carlo'
      fullPath: '/monte-carlo'
      preLoaderRoute: typeof MonteCarloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intelligence': {
      id: '/intelligence'
      path: '/intelligence'
      fullPath: '/intelligence'
      preLoaderRoute: typeof IntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infrastructure': {
      id: '/infrastructure'
      path: '/infrastructure'
      fullPath: '/infrastructure'
      preLoaderRoute: typeof InfrastructureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecast': {
      id: '/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof ForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-twin': {
      id: '/digital-twin'
      path: '/digital-twin'
      fullPath: '/digital-twin'
      preLoaderRoute: typeof DigitalTwinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/databases': {
      id: '/databases'
      path: '/databases'
      fullPath: '/databases'
      preLoaderRoute: typeof DatabasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-sources': {
      id: '/data-sources'
      path: '/data-sources'
      fullPath: '/data-sources'
      preLoaderRoute: typeof DataSourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-gateway': {
      id: '/api-gateway'
      path: '/api-gateway'
      fullPath: '/api-gateway'
      preLoaderRoute: typeof ApiGatewayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  AgentsRoute: AgentsRoute,
  ApiGatewayRoute: ApiGatewayRoute,
  BillingRoute: BillingRoute,
  DataSourcesRoute: DataSourcesRoute,
  DatabasesRoute: DatabasesRoute,
  DesignSystemRoute: DesignSystemRoute,
  DigitalTwinRoute: DigitalTwinRoute,
  ForecastRoute: ForecastRoute,
  InfrastructureRoute: InfrastructureRoute,
  IntelligenceRoute: IntelligenceRoute,
  ModelsRoute: ModelsRoute,
  MonteCarloRoute: MonteCarloRoute,
  NotificationsRoute: NotificationsRoute,
  OrganizationsRoute: OrganizationsRoute,
  ReportsRoute: ReportsRoute,
  RolesRoute: RolesRoute,
  SecurityRoute: SecurityRoute,
  SettingsRoute: SettingsRoute,
  SimulationsRoute: SimulationsRoute,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
